### ISSUE TITLE
I am not sure it returns the required image data on fileChanged!

### ISSUE THREAD

**Issue by xeroxstar** [DoritoBandito/vuetify-upload-button#16]
After the fileChanged fired, i get this data for image?

lastModified: 1522967919731
lastModifiedDate: Thu Apr 05 2018 18:38:39 GMT-0400 (Eastern Daylight Time) {}
name: "na3.jpg"
size: 472412
type: "image/jpeg"
webkitRelativePath: ""

Where is the image? how i convert it in to base64? How do i display on browser?

**Comment by jacobedawson** [comment]
Hey @xeroxstar, 

Yes I was also having a little bit of trouble working out how to get the button to work, but thank god for MDN & Stack Overflow :)

Essentially I found that in order to actually display a preview of the image / grab the file object you should use the FileReader API (https://developer.mozilla.org/en-US/docs/Web/API/FileReader). There may be other ways to handle this in Vue but this is working perfectly for me.  

Using the FileReader you can extract the data that you want, and then send that blob to your server for saving / processing if needed. Below is how I'm now doing it in my project:

```
// example template:
        <v-layout justify-center align-content-center>
          <img v-if="uploadedImage" height="200" :src="uploadedImage" alt>
          <img v-else height="200" :src="user.avatar" alt="avatar">
        </v-layout>
<upload-btn :fileChangedCallback="fileChanged"></upload-btn>

// in script:
  data: () => ({
    uploadedImage: false,
    imageFile: false
  }),
  methods: {
    fileChanged(file) {
      console.log(file);
      const fr = new FileReader();
      fr.readAsDataURL(file);
      fr.addEventListener("load", () => {
        this.uploadedImage = fr.result;
        this.imageFile = file;
        // you can now do other things with the imageFile, like send it to your server
      });
    }
  },
  components: {
    "upload-btn": UploadButton
  }
```

Thanks to this Stack Overflow answer with a great example, which also handles the case where you may use the "multiple" prop: https://stackoverflow.com/questions/44989162/file-upload-in-vuetify

I hope that helps you & anyone else that comes across this! @DoritoBandito I can make a pull request with this example if you'd like.

**Comment by DoritoBandito** [comment]
Thank you @jacobedawson

If you have the spare time feel free to make a PR updating the readme, otherwise I will get to it when I have some free time. I will create an issue later today.
